version: "3.8"

services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  
    depends_on:
      - php
      - mysql  
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    # ports:
    #   - '3000:9000'  
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env

  frontend:
    build: ./frontend
    container_name: frontend
    ports: 
      - '8080:8080'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true  
    depends_on:
      - php
volumes:
  data:
  logs:






# version: "3.8"

# services:
#   api:
#     image: 'nginx:stable-alpine'
#     ports:
#       - '8000:8000'
#     volumes:
#       - ./api:/var/www/html
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  
#     depends_on:
#       - mysql 
#     # ports:
#     #   - '3000:9000'  
#   mysql:
#     image: mysql:5.7
#   frontend:
#     build: ./frontend
#     container_name: frontend
#     ports: 
#       - '8080:8080'
#     volumes:
#       - ./frontend/src:/app/src
#     stdin_open: true
#     tty: true  
#     depends_on:
#       - api
# volumes:
#   data:
#   logs:



